#!/bin/bash
#
# Plugin to monitor CPU usage, for all users optionnaly excluding some one.
# Based on the cpubyuser plugin
#
# Usage: Place in /etc/munin/node.d/ (or link it there  using ln -s)
#        Optionnaly add this to your /etc/munin/plugin-conf.d/munin-node:
#		[cpubyuser-excluding]
#       env.EXCLUDESYSTEMUSERS 1
#		env.USERSEXCLUDED root yann
#
#    EXCLUDESYSTEMUSERS : exclude all system users (typically when uid < 1000)
#	 USERSEXCLUDED : list of users being excluding from the list of the users to monitor.
#	 You need to also make sure that awk is installed
#
# 2012-11-18 v 1.0 Martin PANEL:
#				- creation based on plugin cpubyuser 2008-12-08 v 1.3.1
#

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo "yes"
	exit
fi

function parseUsers ()
{
    if [[ $EXCLUDESYSTEMUSERS && $EXCLUDESYSTEMUSERS -eq 1 ]]; then
        local l=$(grep "^UID_MIN" /etc/login.defs)
        USERS=$(awk -F':' -v "limit=${l##UID_MIN}" '{ if ( $3 >= limit ) print $1}' /etc/passwd)
    else
        USERS=$(awk -F':' '{ print $1}' /etc/passwd)
    fi
    
    if [ -n "$USERSEXCLUDED" ]; then
        local USEREXCLUDED
        for USEREXCLUDED in $USERSEXCLUDED; do
            USERS=$(echo $USERS | sed "s/\b$USEREXCLUDED\b//g")
        done
    fi
}

if [ "$1" = "config" ]; then
	echo "graph_args --base 1000 -r --lower-limit 0"
	echo "graph_title CPU usage, by user"
	echo "graph_category system"
	echo "graph_info This graph shows CPU usage, for monitored users."
	echo "graph_vlabel %"
	echo "graph_scale no"
	echo "graph_period second"
	parseUsers
	_USERS=${USERS//[-.]/_}
	echo "graph_order $_USERS others"
	FIRSTUSER=1;
	for USER in $USERS "others"; do
		_USER=${USER//[-.]/_}
		echo "${_USER}.label $USER"
		echo "${_USER}.info CPU used by user $USER"
		echo "${_USER}.type GAUGE"
		if [ $FIRSTUSER -eq 1 ]; then
			echo "${_USER}.draw AREA"
			FIRSTUSER=0
		else
			echo "${_USER}.draw STACK"
		fi
	done
	exit
fi

parseUsers
ps -e -o "%C%U" | \
	awk -v USERS="$USERS" '
		{ if ($2 != "USER") CPU_USER[$2]+=$1 }
		END {
			others_sum = 0
			for (user in CPU_USER) {
				m = match(USERS,user)
				if (m != 0) {
					_user=user
					gsub(/[-.]/,"_", _user);
					print _user".value", CPU_USER[user]
				} else
					others_sum += CPU_USER[user]
			}
		print "others.value", others_sum;
	}'
